export const LOGIN = 'APP/LOGIN';
export const LOGOUT = 'APP/LOGOUT';
export const TOGGLE_SIDENAV = 'APP/TOGGLE_SIDENAV';
export const UPDATE_SELECTED_KEYS = 'APP/UPDATE_SELECTED_KEYS';
export const UPDATE_OPENED_KEYS = 'APP/UPDATE_OPENED_KEYS';
